# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('sigla', models.CharField(blank=True, max_length=300, null=True)),
                ('preco', models.CharField(blank=True, max_length=300, null=True)),
                ('oscilacao_dia', models.CharField(blank=True, max_length=300, null=True)),
                ('liquidez', models.CharField(blank=True, max_length=300, null=True)),
                ('ultimo_rendimento', models.CharField(blank=True, max_length=300, null=True)),
                ('dy', models.CharField(blank=True, max_length=300, null=True)),
                ('pl', models.CharField(blank=True, max_length=300, null=True)),
                ('rentabilidade_mes', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_construcao_fundo', models.CharField(blank=True, max_length=300, null=True)),
                ('num_cotas_emitidas', models.CharField(blank=True, max_length=300, null=True)),
                ('vi_cota', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_gestao', models.CharField(blank=True, max_length=300, null=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=300, null=True)),
                ('mandato', models.CharField(blank=True, max_length=300, null=True)),
                ('segmento', models.CharField(blank=True, max_length=300, null=True)),
                ('prazo_duracao', models.CharField(blank=True, max_length=300, null=True)),
                ('taxa_adm', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_1', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_3', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_6', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_12', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_1_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_3_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_6_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_12_p', models.CharField(blank=True, max_length=300, null=True)),
                ('num_ativos', models.CharField(blank=True, max_length=300, null=True)),
                ('num_estados', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('preco', models.CharField(blank=True, max_length=300, null=True)),
                ('oscilacao_dia', models.CharField(blank=True, max_length=300, null=True)),
                ('liquidez', models.CharField(blank=True, max_length=300, null=True)),
                ('ultimo_rendimento', models.CharField(blank=True, max_length=300, null=True)),
                ('dy', models.CharField(blank=True, max_length=300, null=True)),
                ('pl', models.CharField(blank=True, max_length=300, null=True)),
                ('rentabilidade_mes', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_1', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_3', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_6', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_12', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_1_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_3_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_6_p', models.CharField(blank=True, max_length=300, null=True)),
                ('yd_12_p', models.CharField(blank=True, max_length=300, null=True)),
                ('num_ativos', models.CharField(blank=True, max_length=300, null=True)),
                ('num_estados', models.CharField(blank=True, max_length=300, null=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Fundo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
