# Generated by Django 2.2.16 on 2020-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='swarmId',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
