# Generated by Django 2.2.16 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
