# Generated by Django 2.2.16 on 2020-10-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
