# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo',
            name='dy',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='liquidez',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_ativos',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_cotas_emitidas',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_estados',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='oscilacao_dia',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='preco',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='rentabilidade_mes',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='ultimo_rendimento',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='vi_cota',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_1',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12_p',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_1_p',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3_p',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6_p',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
