# Generated by Django 2.2.16 on 2020-11-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buff_buff_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buff',
            name='buff_link',
        ),
        migrations.CreateModel(
            name='Ts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Buff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
