# Generated by Django 2.2.16 on 2020-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_channel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='url_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='url_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='url_site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
