# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190722_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo',
            name='yd_1',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_1'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_12'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_12_p'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_1_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_1_p'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_3'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_3_p'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_6'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='dy_6_p'),
        ),
    ]
