# Generated by Django 2.2.16 on 2020-11-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_url_m3u8'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkserie',
            name='m3u8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
