# Generated by Django 2.2.16 on 2020-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filme_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
