# Generated by Django 2.2.16 on 2020-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201110_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='buff',
            name='head',
            field=models.BooleanField(default=False),
        ),
    ]
