# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('dy', models.CharField(blank=True, max_length=300, null=True)),
                ('data_pay', models.CharField(blank=True, max_length=300, null=True)),
                ('rend', models.CharField(blank=True, max_length=300, null=True)),
                ('data_base', models.CharField(blank=True, max_length=300, null=True)),
                ('close', models.CharField(blank=True, max_length=300, null=True)),
                ('rend_cota_mes', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fundo',
            name='dy',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_ativos',
            field=models.IntegerField(blank=True, max_length=300, null=True, verbose_name='N\xfamero de Ativos'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_cotas_emitidas',
            field=models.IntegerField(blank=True, max_length=300, null=True, verbose_name='N\xfamero de Cotas'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='num_estados',
            field=models.IntegerField(blank=True, max_length=300, null=True, verbose_name='N\xfamero de Estados'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='oscilacao_dia',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='Oscila\xe7\xe3o do dia (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='pl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Patrim\xf4nio L\xedquido'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='prazo_duracao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Prazo de Dura\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='P\xfablico Alvo'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='rentabilidade_mes',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='Rentabilidade no M\xeas (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='taxa_adm',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Taxa de Admin.'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='tipo_gestao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tipo de Gest\xe3o'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='ultimo_rendimento',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='\xdaltimo Rendimento (R$)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='vi_cota',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='Valor Inicial da Cota'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_1',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 1 (R$)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 12 (R$)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_12_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 12 (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_1_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 1 (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 3 (R$)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_3_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 3 (%)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 6 (R$)'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='yd_6_p',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='DY 6 (%)'),
        ),
        migrations.AddField(
            model_name='infofundo',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Fundo'),
        ),
    ]
