# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190919_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofundo',
            name='rend_cota_mes_12',
        ),
        migrations.RemoveField(
            model_name='infofundo',
            name='rend_cota_mes_total',
        ),
    ]
